apiVersion: v1
kind: Service
metadata:
  name: kubernetes-backend
spec:
  selector:
    app: kubernetes
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
        - name: kubecontainer
          image: coderhouse:1.0.0
          resources:
            limits:
              memory: 512Mi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8080
          env:
            - name: MONGO
              value: MONGO_URL=mongodb+srv://alejandrolunadev:pfwQvJva1TiliUf5@cluster0.jqvmrup.mongodb.net/ecommerceDB_NAME=ecommers
            - name: JWT_KEY
              value: "SecretCoderKey"
            - name: JWT_RESET_PASSWORD_KEY
              value: "resetPassword2190"
            - name: JWT_COOKIE_KEY
              value: "coderCookie"
            - name: GITHUB_CLIENT_ID
              value: "Iv23liGoznCtJmqx3pQi"
            - name: GITHUB_CLIENT_SECRET
              value: "8e2f6b6a32ae1c34c2cdd62099050ef93b8aeffc"
            - name: GITHUB_CALLBACK_URL
              value: "http://localhost:8080/api/sessions/callbackGitHub"
            - name: PERSISTENCE
              value: "MONGO"
            - name: NODEMAILER_GMAIL
              value: "silousotec@gmail.com"
            - name: NODEMAILER_PASS
              value: "tcjg yasu dsfb mbwv"
          imagePullPolicy: Always
